config/routes.rb
Rails.application.routes.draw do


  root 'welcome#index'

  #just did this for practice
  #post 'event_comments_create' => 'comments#custom_create'

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  
  resources :events do

    resources :comments do

    end

    member do
      get :download
    end
  end

  resources :images do
    resources :comments
    resources :tags

    get :autocomplete_tag_name, :on => :collection


    member do
      get :download
    end
  end

  
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  mount_uploader :event_image, EventImageUploader
  has_many :comments, as: :commentable
  accepts_nested_attributes_for :comments

  validates_presence_of :name
  validates_presence_of :event_date
  
  def self.desc
    Event.all.reverse_order
  end

  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = current_user.events.shuffle
    respond_to do | format |  
        format.js {}  
    end
  end

  def new
    @new_event = Event.new
  end

  def create
    @new_event = Event.new(event_params)
    if @new_event.save
      redirect_to events_path
    else
      render new_event_path, notice: "Something is amiss. Please try again."
    end
  end

  def show
    @event = Event.find(params[:id])
    @commentable = @event
    @comments = @commentable.comments
    @comment = Comment.new
    @new_comment = @event.comments.build
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path
    else
      redirect_to edit_event_path(@event), notice: "Something went Kablooey. Aw man."
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      redirect_to events_path
    else
      redirect_to edit_event_path(@event), notice: "This event is hard to kill. Please try again."
    end
  end

  def download
   @event = Event.find(params[:id])
    file = @event.event_image
    send_file file.path
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :event_date, :event_image, :user_id)
  end


end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/_form.html.haml
%br
= f.label :name
= f.text_field :name, class: "form-control"
%br
= f.label :description
= f.text_area :description, class: "form-control"
%br
= f.label :event_date
= f.date_select :event_date, class: "form-control"
%br
%br
= f.label "Upload an image for your event"
= f.file_field :event_image, class: "form-control"
%br
= f.hidden_field :user_id, value: current_user.id
= f.submit type:'submit', class: "btn btn-default"
%br
%br

app/views/events/_index.html.haml
.container
  .row
    %h1 Your Runs
    = link_to "Create a New Run", new_event_path, class: "btn btn-default"
    %br
    %br
    #image_container
      -@events.each do |event|
        = link_to (image_tag event.event_image.url(:regular), class: 'item'), event_path(event)
        
:javascript
  $(function() {
    var wall = new freewall("#image_container");
    wall.fitWidth();
    });

app/views/events/edit.html.haml
.col-lg-6.col-md-6.col-lg-offset-3.col-md-offset-3.panel.panel-default
  %h1 Edit Run
  = form_for @event do |f|
    = render "form", f: f

app/views/events/index.html.haml
.container
  .row
    %h1 Your Runs
    = link_to "Create a New Run", new_event_path, class: "btn btn-default"
    %br
    %br
    #image_container
      -@events.each do |event|
        = link_to (image_tag event.event_image.url(:regular), class: 'item'), event_path(event)
        
:javascript
  $(function() {
    var wall = new freewall("#image_container");
    wall.fitWidth();
    });

app/views/events/new.html.haml
.col-lg-6.col-md-6.col-lg-offset-3.col-md-offset-3.panel.panel-default
  %h1 New Run

  = form_for @new_event do |f|
    = render "form", f: f

app/views/events/show.html.haml
.col-md-3.col-md-offset-2
  %h3= @event.name | 
  = time_ago_in_words @event.event_date
  = "ago"
  %br

  = image_tag @event.event_image.url, :style => "max-width: 100%"
  %br
  = @event.description
  %br
  




  = render "comments/comments"

  Add a Comment
  %br
  %br
  = render "comments/form"



.col-md-3
  %br
  %br
  = button_to 'Delete this event', event_path(@event), method: "delete", data: { confirm: "Are you sure?" }, class: "btn btn-primary form-control"
  %br
  = link_to "Edit this event", edit_event_path(@event), class: "btn btn-primary form-control"
  %br
  %br
  = link_to "Download event", download_event_path, class: "btn btn-primary form-control"
  %br
  %br
 
 