config/routes.rb
Rails.application.routes.draw do


  root 'welcome#index'

  #just did this for practice
  #post 'event_comments_create' => 'comments#custom_create'

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  
  resources :events do

    resources :comments do

    end

    member do
      get :download
    end
  end

  resources :images do
    resources :comments
    resources :tags

    get :autocomplete_tag_name, :on => :collection


    member do
      get :download
    end
  end

  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :images
  validates :name, length: { minimum: 2 }, allow_blank: false, allow_nil: false

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :load_image

  def index
    @image = @current_image
    @tags = @image.tags
  end

  def new
    @image = @current_image
    @tag = @image.tags.new
  end

  def create
    @image = @current_image
    tag = Tag.where(name: tags_params[:name]).first_or_create
    if @image.tags << tag
      redirect_to @current_image, notice: "Comment created"
    else
      render :new
    end
  end


  private 

  def load_image
    resource, id = request.path.split('/')[1,2]
    @current_image = resource.singularize.classify.constantize.find(id)
  end

  def tags_params
    params.require(:tag).permit(:name)
  end

end

app/views/tags/_form.html.haml
= form_for [@image, @tag] do |f|
  = f.label "Add a Tag"
  %br
  = f.autocomplete_field :name, autocomplete_tag_name_images_path
  %br
  = f.submit

app/views/tags/_tags.html.haml
#tags
  %b Tags:
  - @tags.each do |tag|
    - if tag.name.present?
      %span.custom_tag= tag.name 

app/views/tags/index.html.haml
= render 'tags'

app/views/tags/new.html.haml
= form_for [@image, @tag]  do |f|

  = f.text_area :name
  = f.submit