config/routes.rb
Rails.application.routes.draw do


  root 'welcome#index'

  #just did this for practice
  #post 'event_comments_create' => 'comments#custom_create'

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  
  resources :events do

    resources :comments do

    end

    member do
      get :download
    end
  end

  resources :images do
    resources :comments
    resources :tags

    get :autocomplete_tag_name, :on => :collection


    member do
      get :download
    end
  end

  
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_and_belongs_to_many :tags
  has_many :comments, as: :commentable
  belongs_to :user
  accepts_nested_attributes_for :tags, :reject_if => :all_blank
  mount_uploader :image_data, ImageDataUploader

  validates_presence_of :title
  
  #how to implement?
  #default_scope { order('image_date DESC') } 

  def self.descending
    Image.order('image_date DESC').all
  end

  def self.recent_images
    Image.last(4).reverse
  end
  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  autocomplete :tag, :name
  
  def index
    @images = Image.all
    respond_to do | format | 
        format.html 
        format.js 
    end
  end

  def new
    @new_image = Image.new
    @new_image.tags.build
  end

  def create
    @new_image = Image.new(image_params)
    if @new_image.save
      redirect_to image_path(@new_image)
    else
      redirect_to new_image_path(@new_image), notice: "Something is amiss. Please try again."
    end
  end

  def show
    # if owned_by_current_user?(params[:id])
      @image = Image.find(params[:id])
      @commentable = @image
      @comments = @commentable.comments
      @comment = Comment.new

      @tags = @image.tags
      @tag = Tag.new

      respond_to do |format|
        format.html
        format.js
      end
    # else
    #   redirect_to root_path, notice: "You don't appear to be the owner of this image."
    # end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      redirect_to image_path
    else
      redirect_to edit_image_path(@image), notice: "Something went Kablooey. Aw man."
    end
  end

  def destroy
    @image = Image.find(params[:id])
    if @image.destroy
      redirect_to images_path
    else
      redirect_to edit_image_path(@image), notice: "This image is hard to kill. Please try again."
    end
  end

  def download
   @image = Image.find(params[:id])
    file = @image.image_data
    send_file file.path
  end

  private
  # to implement
  # def owned_by_current_user?(image_id)
  #   image = Image.find(image_id)
  #   image.user_id == current_user.id 
  # end

  def image_params
    params.require(:image).permit(:title, :description, :image_date, :image_data, :user_id, tags_attributes: [:id, :name, :_destroy])
  end


end

app/helpers/image_helper.rb
module ImageHelper
end

app/views/images/_index.html.haml
.container
  .row
    %h1 Your Images

    = link_to "Create a New Image", new_image_path, class: "btn btn-default"
    %br
    %br

    - current_user.images.each do |i|
      .col-md-4
        .panel.panel-info
          .panel-heading
            = link_to "#{i.title}, #{time_ago_in_words(i.image_date)} ago", image_path(i)
            %br
            %br
          .panel-body
            = image_tag i.image_data.url(:regular)

            %br
          .panel-footer
            = i.description
            %br
            %br

app/views/images/edit.html.haml
%h1 Image#edit
%p Find me in app/views/image/edit.html.haml

app/views/images/index.html.haml
.container
  .row
    %h1 Your Images

    = link_to "Create a New Image", new_image_path, class: "btn btn-default"
    %br
    %br

    - current_user.images.each do |i|
      .col-md-4
        .panel.panel-info
          .panel-heading
            = link_to "#{i.title}, #{time_ago_in_words(i.image_date)} ago", image_path(i)
            %br
            %br
          .panel-body
            = image_tag i.image_data.url(:regular)

            %br
          .panel-footer
            = i.description
            %br
            %br

app/views/images/new.html.haml
.col-lg-6.col-md-6.col-lg-offset-3.col-md-offset-3.panel.panel-default

  %h1 New Image

  = nested_form_for @new_image do |f|
    = f.label :title
    = f.text_field :title, class: "form-control"
    %br
    = f.label :description
    = f.text_area :description, class: "form-control"
    %br
    = f.label :image_date
    = f.date_select :image_date, class: "form-control"
    %br
    = f.label "Choose your image:"
    = f.file_field :image_data
    = f.hidden_field :user_id, value: current_user.id
    %br

    =f.fields_for :tags, @new_image.tags.build do |t|
      = t.text_field :name, class: "form-control"
      = t.link_to_remove "Remove this tag"
      %br
      %br
    = f.link_to_add "Add a tag", :tags
    %br
    %br
    = f.submit

app/views/images/show.html.haml
.col-md-3.col-md-offset-3
  %h3{data: {id: '5'}}= @image.title, 
  = time_ago_in_words @image.image_date
  = "ago"
  %br

  = image_tag @image.image_data.url, :style => "max-width: 100%"
  %br
  %span{data: {id: '5'}}= @image.description
  %br
  




  = render "comments/comments"

  Add a Comment
  %br
  %br
  = render "comments/form"



.col-md-3
  %br
  %br
  = button_to 'Delete this Image', image_path(@image), method: "delete", data: { confirm: "Are you sure?" }, class: "btn btn-primary form-control"
  %br
  = link_to "Edit this Image", edit_image_path(@image), class: "btn btn-primary form-control"
  %br
  %br
  = link_to "Download Image", download_image_path, class: "btn btn-primary form-control"
  %br
  %br
  = render "tags/tags"
  %br
  %br
  %br
  = render "tags/form"
 

:coffee
  $("[data-id]").click ->
    alert('hello')