config/routes.rb
Rails.application.routes.draw do


  root 'welcome#index'

  #just did this for practice
  #post 'event_comments_create' => 'comments#custom_create'

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  
  resources :events do

    resources :comments do

    end

    member do
      get :download
    end
  end

  resources :images do
    resources :comments
    resources :tags

    get :autocomplete_tag_name, :on => :collection


    member do
      get :download
    end
  end

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Visual Running Log</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '/assets/jquery-1.10.2.min.js' %>
  <%= javascript_include_tag '/assets/freewall.js' %>
  <%= csrf_meta_tags %>
</head>
<body >
  <nav class="navbar navbar-default" role="navigation">
    <a class="navbar-brand" href="/">Visual Running Log</a>
    <ul class="nav navbar-nav">
      <li class="white_nav">
        <%= link_to "Your Runs", events_path, remote: true, class: "white_nav" %>
      </li>
      <li >
        <%= link_to "Your Images", images_path, remote: true, class: "white_nav"%>
      </li>
    </ul>

    <% if current_user %>
      <%= "Logged in as #{current_user.email}" %>
      <%= link_to "Log Out", logout_path, class: "white_nav" %>
    <% else %>
      <button class="btn btn-default btn-md custom_nav" data-toggle="modal" data-target="#login">Login</button>
      <button class="btn btn-default btn-md custom_nav" data-toggle="modal" data-target="#signup">Signup</button>
    <% end %>
  </nav>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>



<div class="add_top_margin">


    <%= yield %>

</div>






</body>
</html>